#!/bin/bash

#List here all the f90 files to compile, separated by spaces
#THERE MUST NOT be spaces around '=' in bash
myprogramfiles="read_inputs.f90 nc_output.f90 finite_diff_solver.f90"
#Name of compiled file
outfile="finite_diff_solver"

#Name of compiler
fc=gfortran
#Use nf-config to grab the compile and link flags. Backticks run command and grab output
fflags=`nf-config --fflags`
flibs=`nf-config --flibs`

#Actual compile line. Other flags etc can be added

#$fc -std=f2008 $fflags $myprogramfiles $flibs -lnetcdf -llapack -o $outfile || { echo 'Compilation failed.' ; return 1; }
make
#run line
python3 user_input.py

#plot

#clean (option)
#make clean
